# Generated by Django 4.2.7 on 2025-01-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_title', models.CharField(max_length=255)),
                ('segment_name', models.CharField(help_text='Segment of the property, e.g., Residential, Commercial', max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=50)),
                ('area', models.CharField(help_text='Area of the property, e.g., 2000 sq ft', max_length=50)),
                ('location', models.CharField(help_text='Enter the location of the property', max_length=255)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the property', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the property', null=True)),
                ('facilities', models.JSONField(default=list, help_text="Facilities available at the property, e.g., ['living room', 'swimming pool', 'kitchen']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
